/** @type {import('tailwindcss').Config} */
const colorVar = (name) => `rgb(var(${name}) / <alpha-value>)`;

export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"IBM Plex Sans Arabic"', 'Tajawal', 'Cairo', 'sans-serif'],
      },
      colors: {
        primary: {
          DEFAULT: colorVar('--color-primary'),
          50: colorVar('--color-primary-50'),
          100: colorVar('--color-primary-100'),
          200: colorVar('--color-primary-200'),
          300: colorVar('--color-primary-300'),
          400: colorVar('--color-primary-400'),
          500: colorVar('--color-primary-500'),
          600: colorVar('--color-primary-600'),
          700: colorVar('--color-primary-700'),
          800: colorVar('--color-primary-800'),
          900: colorVar('--color-primary-900'),
          950: colorVar('--color-primary-950'),
        },
        secondary: {
          DEFAULT: colorVar('--color-secondary'),
          50: colorVar('--color-primary-50'),
          100: colorVar('--color-primary-100'),
          500: colorVar('--color-secondary'),
          600: colorVar('--color-primary-600'),
          700: colorVar('--color-primary-700'),
        },
        accent: {
          DEFAULT: colorVar('--color-accent'),
          50: colorVar('--color-success-50'),
          500: colorVar('--color-accent'),
          600: colorVar('--color-success-600'),
        },
        background: colorVar('--color-background'),
        surface: {
          DEFAULT: colorVar('--color-surface'),
          muted: colorVar('--color-surface-muted'),
          elevated: colorVar('--color-surface-elevated'),
        },
        hover: colorVar('--color-hover'),
        'text-primary': colorVar('--color-text-primary'),
        'text-secondary': colorVar('--color-text-secondary'),
        'text-muted': colorVar('--color-text-muted'),
        border: colorVar('--color-border'),
        success: {
          DEFAULT: colorVar('--color-success'),
          50: colorVar('--color-success-50'),
          500: colorVar('--color-success-500'),
          600: colorVar('--color-success-600'),
        },
        warning: {
          DEFAULT: colorVar('--color-warning'),
          50: colorVar('--color-warning-50'),
          500: colorVar('--color-warning-500'),
          600: colorVar('--color-warning-600'),
        },
        danger: {
          DEFAULT: colorVar('--color-danger'),
          50: colorVar('--color-danger-50'),
          500: colorVar('--color-danger-500'),
          600: colorVar('--color-danger-600'),
        },
        info: {
          DEFAULT: colorVar('--color-info'),
          50: colorVar('--color-info-50'),
          500: colorVar('--color-info-500'),
          600: colorVar('--color-info-600'),
        },
        shift: {
          morning: '#22C55E',
          evening: '#F59E0B',
          night: '#8B5CF6',
          oncall: '#2563EB',
          overtime: '#F97316',
          vacation: '#94A3B8',
          sick: '#EF4444',
          training: '#06B6D4',
        },
        ink: colorVar('--color-ink'),
        'primary-teal': colorVar('--color-primary-teal'),
        'signal-cyan': colorVar('--color-signal-cyan'),
        'warm-surface': colorVar('--color-warm-surface'),
        'slate-brand': colorVar('--color-slate-brand'),
        'alert-coral': colorVar('--color-alert-coral'),
        'facility-kamc': 'var(--facility-kamc)',
        'facility-kasch': 'var(--facility-kasch)',
        'facility-whh': 'var(--facility-whh)',
      },
      borderRadius: {
        DEFAULT: '8px',
        card: '8px',
        btn: '8px',
        pill: '9999px',
      },
      boxShadow: {
        soft: '0 1px 2px rgb(var(--color-shadow) / 0.05)',
        card: '0 1px 2px rgb(var(--color-shadow) / 0.04)',
        dropdown: '0 18px 36px -24px rgb(var(--color-shadow) / 0.46), 0 6px 16px -12px rgb(var(--color-shadow) / 0.28)',
      },
    },
  },
  plugins: [],
};
