import { useTranslation } from 'react-i18next';
import type { DepartmentScheduleView } from '@/types/employeeScheduleView';

interface Props { view: DepartmentScheduleView; locale: string; selfEmployeeId?: string }

export default function DepartmentScheduleDesktop({ view, locale, selfEmployeeId }: Props) {
  const { t } = useTranslation('schedule');
  return <div className="hidden overflow-x-auto rounded-card border border-border bg-surface shadow-card md:block"><table className="w-full min-w-[860px] border-collapse text-sm"><thead className="sticky top-0 z-10 bg-surface-muted"><tr><th className="w-44 border-b border-border px-4 py-3 text-start text-xs font-semibold text-text-secondary">{t('departmentView.date')}</th>{['day', 'late', 'night', 'onCallDay', 'onCallNight', 'ot'].map((category) => <th key={category} className="border-b border-border px-3 py-3 text-start text-xs font-semibold text-text-secondary">{t(`departmentView.categories.${category}`)}</th>)}</tr></thead><tbody className="divide-y divide-border/60">{view.days.map((day) => <tr key={day.date} className="align-top"><th className="sticky start-0 bg-surface px-4 py-4 text-start font-medium text-text-primary"><time dateTime={day.date}>{new Intl.DateTimeFormat(locale, { weekday: 'short', month: 'short', day: 'numeric' }).format(new Date(`${day.date}T12:00:00`))}</time></th>{['day', 'late', 'night', 'onCallDay', 'onCallNight', 'ot'].map((category) => { const group = day.groups.find((entry) => entry.category === category); return <td key={category} className="px-3 py-3">{group?.occurrences.map((occurrence) => { const self = occurrence.employeeId === selfEmployeeId; return <div key={occurrence.id} className={self ? 'mb-2 rounded-btn border border-primary/30 bg-primary-50 p-2 ring-1 ring-primary/10' : 'mb-2 rounded-btn bg-background p-2'}><div className="flex flex-wrap items-center gap-1"><span className="font-semibold text-text-primary">{occurrence.employeeName || occurrence.employeeCode}</span>{self && <span className="rounded-full bg-primary px-1.5 py-0.5 text-[10px] font-semibold text-white">{t('departmentView.you')}</span>}{occurrence.source === 'ot' && <span className="rounded-full bg-info/10 px-1.5 py-0.5 text-[10px] font-semibold text-info">OT</span>}</div><p className="mt-1 text-[11px] text-text-secondary">{occurrence.facility} · {occurrence.unit}</p><p className="mt-0.5 text-[11px] text-text-secondary" dir="ltr">{occurrence.timeRange}</p></div>; })}</td>; })}</tr>)}</tbody></table></div>;
}
